### ISSUE TITLE
upgrade to version = "0.23.4"

### ISSUE THREAD

**Issue by tb102122** [diagrams-web/diagrams-xtd#2]
Hey @gabriel-tessier ,

can we upgrade to the latest version of the original branch?
Does that work for you?

Cheers Tobi

**Comment by gabriel-tessier** [comment]
@tb102122 

Thanks for the help and the interest in the project.
I will  make the last check and merge this week.

**Comment by tb102122** [comment]
#1 waiting for

**Comment by gabriel-tessier** [comment]
let's close it after the merge.

**Comment by gabriel-tessier** [comment]
@tb102122 

I released one version if you have time to validate that it's working not only on my computer.

https://github.com/diagrams-web/diagrams-xtd/releases/tag/0.23.4.6

I used poetry and I'm not yet at ease with the tool, usually I use pip, and sorry for the delay as I didn't touch the project from a while I need to update some dependencies and my knowledge.

I also released the 0.22.x version, it's the one used on diagrams-web.

**Comment by tb102122** [comment]
@gabriel-tessier I had some trouble in your tag to find the latest source code.
I have created 2 new PRs for you with the latest version #4  and #5 with actions.
One the publishing action you still need to revise the variable for the pypi access key.
I hope I have not overwritten some of the changes you did, I was careful with the updates and checked the last commits from our side.

**Comment by gabriel-tessier** [comment]
@tb102122 

Sorry my message was maybe confusing, the tag link is a link to the release for you to test it.

First you need to download the tag.gz file  **"diagrams-0.23.4.6.tar.gz"**
Then create a new virtual environment for test. 
and run `pip install diagrams-0.23.4.6.tar.gz`

I was not sure about the build as I used poetry for the fist time and I did not build package from long time. My objective was only to validate that the release was working correctly.

I also wonder if I can publish it on Pypi with diagrams-xtd name and how it will work, if the code need to be "from diagrams-xtd imoprt xxx" which can break some code. But it should be ok as it's a fork. There's still some work before releasing a stable version.
So First step was to validate that the base package was working I don't wan to publish something broken.
I will add it in the diagrams-web and check with my already made diagrams and other example.

I will check the PR you opened and try to finish this during the weekend.
Thanks again for your help.

**Comment by tb102122** [comment]
Yes than we misunderstood each other.
Pypi has a test api which we can use to test the releases https://stackoverflow.com/questions/68882603/using-python-poetry-to-publish-to-test-pypi-org

**Comment by gabriel-tessier** [comment]
Merged
